#cloud-config
users:
  - name: ubuntu #username
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo-regeln für den user
    groups: users, admin #Gruppen in dem der User drin ist
    home: /home/ubuntu #Homeverzeichnis
    shell: /bin/bash #Standart Konsolentyp
    ssh_authorized_keys: #öffentlicher SSH-Schlüssel für die Authentifiezierung
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCH4J/53gzoLdFvuSI/4l7ACEbv6FCJ30myoYGMwkSB+p0qtpvutbFKaCSzxhMf9Dt6ynNiOsO0niYfO1ADn3Q7m9d/+ysTG5U4AsNkRcIWvM7+dV07EkKu/Z5GILgJlqSQqmR13F5R0nFGZdPEKTbWzlrBlGcBNbPUBD8ndyC2NTyyVE96jLSOUqtHsmBw+qmGPoayplU1TFawBPS/fpWFSmHVZWf3awAZ/GPpG/6DsEPBdMOHIfc/SV8pEDJOj8iYHAplxPtqLnKugwrrI/tinNseFzE7eTEEohf2PDK1g0ctHopyg5WqLdMWzyDsdUUAmM3lfU1wEkEEr92IIWSz aws-key   
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD # öffentlicher Schlüssel NUY    
ssh_pwauth: false #kein Passwort muss eingegeben werden, wenn mit SSH-Schlüssel authentifiziert
disable_root: false #Root Zugriff ist gegeben
package_update: true #Packages werden beim neu start updated
packages: #Packages die Heruntergeladen werden sollen 
  - curl #curl wird installiiert
  - wget #wgtet wird installiert
