#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: users, admin 
    home: /home/ubuntu 
    shell: /bin/bash 
    ssh_authorized_keys: 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCH4J/53gzoLdFvuSI/4l7ACEbv6FCJ30myoYGMwkSB+p0qtpvutbFKaCSzxhMf9Dt6ynNiOsO0niYfO1ADn3Q7m9d/+ysTG5U4AsNkRcIWvM7+dV07EkKu/Z5GILgJlqSQqmR13F5R0nFGZdPEKTbWzlrBlGcBNbPUBD8ndyC2NTyyVE96jLSOUqtHsmBw+qmGPoayplU1TFawBPS/fpWFSmHVZWf3awAZ/GPpG/6DsEPBdMOHIfc/SV8pEDJOj8iYHAplxPtqLnKugwrrI/tinNseFzE7eTEEohf2PDK1g0ctHopyg5WqLdMWzyDsdUUAmM3lfU1wEkEEr92IIWSz aws-key       
ssh_pwauth: false 
disable_root: false 
package_update: true 
packages:  
  - curl 
  - wget 
